files:
  - source: /_locales/en/*.json
    translation: /_locales/%two_letters_code%/%original_file_name%
    languages_mapping:
      - two_letters_code:
          - en-AU: en_AU
            en-GB: en_GB
            en-US: en_US
            pt-BR: pt_BR
            pt-PT: pt_PT
            zh-CN: zh_CN
            zh-TW: zh_TW
